# PDD is a platform for privacy-preserving Web searches collection.
# Copyright (C) 2016-2018 Vincent Primault <v.primault@ucl.ac.uk>
#
# PDD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PDD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PDD.  If not, see <http://www.gnu.org/licenses/>.

title: Private Data Donor
email: pddisense@ucl.ac.uk
description: >
  Private Data Donor is a research project whose goal is to collect data in a privacy-preserving way,
  in order to identify outbreaks of infectious diseases much earlier than ever before.
baseurl: ""
url: "https://ppd.cs.ucl.ac.uk"

markdown: kramdown
gems:
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- BUILD
